# This playbook deploys a complete production line
# ansible-playbook -i localhost, deploy_services_01.yaml --connection=local

- name: Deploy Service Commissioning Files
  hosts: localhost                               # Run all tasks on the local machine
  # hosts: local_network                         # Alternative: run from a client on the same network
  gather_facts: false

  vars:
    target_hostname: localhost:443
    validate_certs: false

  tasks:
    - name: Deploy Welding Robots
      loop:
        - id: weldingRobot01_05
          commissioning_file: ./05_welding_05.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1101
          organization: "carfactory"
          location: "plant1"
          processarea: "weldingShop"
          equipment: "weldingRobot01"
        - id: weldingRobot02_05
          commissioning_file: ./05_welding_05.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1101
          organization: "carfactory"
          location: "plant1"
          processarea: "weldingShop"
          equipment: "weldingRobot02"             
      loop_control:
        loop_var: welding
      cybus.connectware.service:
        id: "{{ welding.id }}"
        commissioning_file: "{{ welding.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ welding.plcHost }}"
          plcPort: 1101
          organization: "{{ welding.organization }}"
          location: "{{ welding.location }}"
          processarea: "{{ welding.processarea }}"
          equipment: "{{ welding.equipment }}"

    - name: Deploy Storage Systems
      loop:
        - id: highbay01
          commissioning_file: ./06_storage.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1107
          organization: "carfactory"
          location: "plant1"
          processarea: "warehouse"
          equipment: "highbay01"
      loop_control:
        loop_var: storage
      cybus.connectware.service:
        id: "{{ storage.id }}"
        commissioning_file: "{{ storage.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ storage.plcHost }}"
          plcPort: 1107
          organization: "{{ storage.organization }}"
          location: "{{ storage.location }}"
          processarea: "{{ storage.processarea }}"
          equipment: "{{ storage.equipment }}"

    - name: Deploy AGVs
      loop:
        - id: agv01
          commissioning_file: ./07_agv.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1108
          organization: "carfactory"
          location: "plant1"
          processarea: "intralogistics"
          equipment: "agv01"
      loop_control:
        loop_var: agv
      cybus.connectware.service:
        id: "{{ agv.id }}"
        commissioning_file: "{{ agv.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ agv.plcHost }}"
          plcPort: 1108
          organization: "{{ agv.organization }}"
          location: "{{ agv.location }}"
          processarea: "{{ agv.processarea }}"
          equipment: "{{ agv.equipment }}"

    - name: Deploy Punching Machines
      loop:
        - id: punchingmachine01
          commissioning_file: ./08_punching.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1102
          organization: "carfactory"
          location: "plant1"
          processarea: "pressShop"
          equipment: "punchingMachine01"
      loop_control:
        loop_var: punching
      cybus.connectware.service:
        id: "{{ punching.id }}"
        commissioning_file: "{{ punching.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ punching.plcHost }}"
          plcPort: 1102
          organization: "{{ punching.organization }}"
          location: "{{ punching.location }}"
          processarea: "{{ punching.processarea }}"
          equipment: "{{ punching.equipment }}"

    - name: Deploy Painting Cells
      loop:
        - id: paintingCell01
          commissioning_file: ./09_painting.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1105
          organization: "carfactory"
          location: "plant1"
          processarea: "coatingShop"
          equipment: "paintingCell01"
      loop_control:
        loop_var: painting
      cybus.connectware.service:
        id: "{{ painting.id }}"
        commissioning_file: "{{ painting.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ painting.plcHost }}"
          plcPort: 1105
          organization: "{{ painting.organization }}"
          location: "{{ painting.location }}"
          processarea: "{{ painting.processarea }}"
          equipment: "{{ painting.equipment }}"

    - name: Deploy Inspection Machines
      loop:
        - id: inspectionMachine01
          commissioning_file: ./10_inspection.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1104
          organization: "carfactory"
          location: "plant1"
          processarea: "qualityControl"
          equipment: "inspectionMachine01"
      loop_control:
        loop_var: inspection
      cybus.connectware.service:
        id: "{{ inspection.id }}"
        commissioning_file: "{{ inspection.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ inspection.plcHost }}"
          plcPort: 1104
          organization: "{{ inspection.organization }}"
          location: "{{ inspection.location }}"
          processarea: "{{ inspection.processarea }}"
          equipment: "{{ inspection.equipment }}"

    - name: Deploy Packaging Cells
      loop:
        - id: packagingcell01
          commissioning_file: ./11_packaging.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1103
          organization: "carfactory"
          location: "plant1"
          processarea: "packaging"
          equipment: "packagingCell01"
      loop_control:
        loop_var: packaging
      cybus.connectware.service:
        id: "{{ packaging.id }}"
        commissioning_file: "{{ packaging.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ packaging.plcHost }}"
          plcPort: 1103
          organization: "{{ packaging.organization }}"
          location: "{{ packaging.location }}"
          processarea: "{{ packaging.processarea }}"
          equipment: "{{ packaging.equipment }}"

    - name: Deploy Finished Goods Warehouse
      loop:
        - id: finishedGoodsWarehouse01
          commissioning_file: ./12_warehouse.cw.yaml
          plcHost: "192.168.3.139"
          plcPort: 1106
          organization: "carfactory"
          location: "plant1"
          processarea: "finishedGoodsWarehouse"
          equipment: "storage01"
      loop_control:
        loop_var: warehouse
      cybus.connectware.service:
        id: "{{ warehouse.id }}"
        commissioning_file: "{{ warehouse.commissioning_file }}"
        enabled: true
        target_hostname: "{{ target_hostname }}"
        validate_certs: "{{ validate_certs }}"
        parameters:
          plcHost: "{{ warehouse.plcHost }}"
          plcPort: 1106
          organization: "{{ warehouse.organization }}"
          location: "{{ warehouse.location }}"
          processarea: "{{ warehouse.processarea }}"
          equipment: "{{ warehouse.equipment }}"
